### ISSUE TITLE
Cl computation for nonzero wa_fld in python

### ISSUE THREAD

**Issue by kgage** [lesgourg/class_public#103]
I am attempting to calculate the Cls for a cosmology with wa = 0.5 via the classy wrapper.

```
from classy import Class
cosmo = Class()
cosmo.set(param_dict)
cosmo.compute()
result = cosmo.raw_cl(2500)
cosmo.struct_cleanup()
```

I am using the following as param_dict to set the parameters:

```
{'N_ncdm': 0,
 'N_ur': 3.04,
 'Omega_Lambda': 0.0,
 'Omega_b': 0.045,
 'Omega_cdm': 0.2219661577649899,
 'Omega_k': 0.0,
 'Omega_scf': 0.0,
 'T_cmb': 2.725,
 'h': 0.71,
 'output': 'tCl,pCl,lCl',
 'w0_fld': -1.0,
 'wa_fld': -0.5}
```

While computing Cls for cosmologies with wa = 0 usually takes ~5 seconds, this ran for ~20 hours before I finally stopped it. I'm fairly certain adding in a nonzero wa shouldn't cause CLASS to take 10^4 times longer to compute the Cls, so I assume something must be wrong.

**Comment by kgage** [comment]
I am running into what seems to be the same issue when attempting to calculate the matter power spectrum mPk. Does anyone have a working example with a nonzero wa_fld using the python wrapper?

**Comment by ThomasTram** [comment]
Hi,

have a look in 
https://github.com/lesgourg/class_public/issues/100
The problem is that the perturbations become unstable (and unphysical) when w crosses -1. In your example w does not cross but becomes arbitrarily close to -1 which is also not allowed. Unfortunately this case is not caught by the class_test(). You will get the following error message if you change w0_fld to -0.99:
````Error in perturb_init 
=>perturb_init(L:191) :condition (((pba->w0_fld + pba->wa_fld +1.0)*(pba->w0_fld+1.0)) < 0.0) is true; w crosses -1 between the infinite past and today, and this would lead to divergent perturbation equations for the fluid.````
This should probably be <= and not <. If you run with w0_fld=-1.01 you will not have  a problem.

Cheers,
Thomas
