### ISSUE TITLE
New error in current version

### ISSUE THREAD

**Issue by aoifeboyle** [lesgourg/class_public#109]
Hi. I have CLASS version 2.4.3 installed on my desktop and the current version on my laptop. Using the current version, I get the following error, although it does not appear for the same input file when using version 2.4.3.

Error in spectra_init 
=>spectra_init(L:1269) :error in spectra_pk(pba,ppt,ppm,pnl,psp);
=>spectra_pk(L:2684) :error in spectra_sigma(pba,ppm,psp,8./pba->h,0.,&(psp->sigma8));
=>spectra_sigma(L:2775) :error in spectra_pk_at_k_and_z(pba,ppm,psp,k,z,&pk,pk_ic);
=>spectra_pk_at_k_and_z(L:683) :error in spectra_pk_at_z(pba, psp, logarithmic, z, spectrum_at_z, spectrum_at_z_ic);
=>spectra_pk_at_z(L:413) :error in array_interpolate_spline(psp->ln_tau, psp->ln_tau_size, psp->ln_pk, psp->ddln_pk, psp->ln_k_size, ln_tau, &last_index, output_tot, psp->ln_k_size, psp->error_message);
=>array_interpolate_spline(L:1701) : x=9.559662e+00 > x_max=9.559662e+00

This is my input file:

output = mPk
write warnings = yes
write background = no

k_per_decade_for_pk = 50 #For fiducial_pk generation
k_per_decade_for_bao = 50 #For fiducial_pk generation

k_min_tau0 = 0.04

P_k_max_h/Mpc = 2.5
z_pk = 0.9
N_ncdm = 3
N_ur = 0.00641

omega_b = 0.02225
omega_cdm = 0.1198
100*theta_s = 1.04077
m_ncdm = 0.00240254932815,0.0112907437455,0.0493067069264
ln10^{10}A_s = 3.094
n_s = 0.9645
tau_reio = 0.079

I can keep using version 2.4.3 for now but I would be curious to know what the cause of this is.

Thanks,

Aoife

**Comment by ThomasTram** [comment]
Hi Aoife,

I cannot reproduce the error. From the error message I think the problem is that the interpolation of the final point in the matter powerspectrum is very slightly outside the interpolation range due to numerical error. You can try adding 
````k_output_values = 2.0````
which would add another point in the k-vector larger than 2.5 h/Mpc. It would be useful if you could list your system (OSX/Windows/Linux, 32bit or 64bit) and the compiler (gcc, icc,...) and its version.

Cheers,
Thomas
