### ISSUE TITLE
matter power spektrum CLASS vs CAMB: how to make them agree at high k

### ISSUE THREAD

**Issue by VMBoehm** [lesgourg/class_public#113]
Hi,
comparing matter power spectra from class and camb (see plot below), I get a discrepancy at high k, which seems the same as in the left panel of Fig 3 in the class-camb comparison paper (https://arxiv.org/abs/1104.2934).
My first question:
Is that correct? Or coudl I be messing up sth else?
And my second question: If that is correct, is there a simple way to fudge Class to make the same reionization approximation (that is apparently causing this)?
Thanks!
Vanessa
![mpk_class_camb](https://cloud.githubusercontent.com/assets/22053912/18313702/3dfb2368-7510-11e6-9dd1-9b4a6c2cfd88.png)

**Comment by ThomasTram** [comment]
Hi Vanessa,

I do not think it is the same effect. Note that the y-axis in Fig. 3 is in %, and from looking at your plot I suspect that you are just plotting the ratio. Also, the comparison paper is now 5 years old, and probably the reionisation impact on the baryon sound speed is now taken into account in CAMB as well. (I did not check this though.)

The problem is that at very large k values, the default precision of the codes are not sufficient. It is expensive, computation wise, to get good precision at these k-values primarily due to the reflection of power from the artificial lmax cut in the Boltzmann hierarchy. If you want to improve the agreement to the level presented in the comparison paper, you need to push the precision of both codes along the lines mentioned in 1104.2934, bearing in mind that both codes evolved during the past 5 years. You can get some inspiration from the precision file pk_ref.pre as well.

Cheers,
Thomas Tram

**Comment by VMBoehm** [comment]
Hi Thomas,
thanks for replying do quickly and for pointing out the difference in the y-axes!  It turned out k_max of the transfer function in camb was set too low. The fraction of percent difference that I get now is perfectly fine for the purpose.
Thanks again!
Cheers,
Vanessa
![mpk_class_camb_new](https://cloud.githubusercontent.com/assets/22053912/18316423/d4d6627a-751a-11e6-8a8c-cd32c468bb69.png)
