### ISSUE TITLE
Integration over time

### ISSUE THREAD

**Issue by borisbolliet** [lesgourg/class_public#114]
Dear All,

I would like to evaluate an integral over time, say the integral of the gravitational potential \phi(k,tau). 

How do I do this in CLASS and what are the relevant precision parameters to include? 

Thank you very much,

Kind regards,
Boris

**Comment by ThomasTram** [comment]
Hi Boris

You should make sure that you get enough time steps to make an accurate integral. The primary parameter would be
````
'perturb_sampling_stepsize':0.01
````
which you may need to decrease a bit if you need higher accuracy. You also need to add all k_values to the k_output variable:
````
k_out = np.logspace(-4,0,40)
'k_output_values':str(k_out).strip('[]'),
````
There is a limitation on how many k_values you can request because the string gets longer than the maximum length of a CLASS input string. But I am sure you can figure out which parameter you need to increase in the relevant ````.h````. Two other ways of getting around this problem: 1) Make the k_array in such a way that the ASCII representation of each k is short. 2) Run several instances of CLASS, each with a fraction of the k-vector.

Cheers,
Thomas
