### ISSUE TITLE
Matter Power Spectrum from Perturbations

### ISSUE THREAD

**Issue by emdemor** [lesgourg/class_public#147]
I need a conceptual help to understand the code. How can I generate the matter power spectrum (in mPk file) through the perturbed variables d_i present in in mTk file? Where do the terms h⁻3 and Mpc ^ 3 that we see in the 2dfgrs data come from?

**Comment by lesgourg** [comment]
Hi!
For your first question: you find this in several papers in the literature, the answer is:
P(k) = <delta_m delta_m> = (2pi^2) k^-3 (delta_m)^2 P_R(k)
where  delta_m is the weighted average of the delta_i's for non-relativistic components (sum_i Omega_i delta_i)/(sum_i Omega_i) and P_R(k) is the primordial curvature power spectrum (since the delta_i's are normalised to R=curvature=1).
For your second question, sorry, I don't understand it.

**Comment by emdemor** [comment]
Thank you! I'm just a student now. I began to study cosmological perturbations a few weeks ago and I am using CLASS to understand the influence of cosmological parameters. I was trying to reproduce the 2dfGRS data through the density contrast and with the answer you gave me everything turned out well. The second question was about the power spectrum units (I used bad terms). With the term k-3, I got them.
