### ISSUE TITLE
theta_s, theta_MC, or theta_star?

### ISSUE THREAD

**Issue by borisbolliet** [lesgourg/class_public#151]
Dear all,

This is a quick and not so important question:

In Planck Cosmological parameters tables there are two different angular scale at decoupling, one is called theta_MC (said to be obtained within CosmoMC approximation, whatever that means), the other is theta_star.

In Class we work with theta_s.

The values of theta_MC, theta_star, theta_s always agree within 68%CL, but for accuracy it would be good to know wether theta_s of Class is theta_MC or theta_star? :-)

Thank you very much,
Boris

**Comment by lesgourg** [comment]
Hi Boris,
I can immediately answer for theta_s[class] and theta_MC[cosmomc].
theta_s[class] is the actual angular scale of the sound horizon at decoupling. This concept obeys to a precise and simple mathematical definition, with an integral over the sound speed, and this is what CLASS computes with good accuracy, performing the full integral, and searching numerically for the time of decoupling, defined as the maximum of the visibility function.
theta_MC[cosmomc] is an approximation to the previous one, based on some old model-dependent analytical fits instead of the full integral. CosmoMC used that calculation at the beginning for simplicity, and then Antony never changed the definition, in order not to confuse regular CosmoMC users, but strictly speaking theta_MC does not represent anything physical in a precise way.
I am not sure about the theta_* of the Planck paper, for that I should have a look - remind me if I forget to answer. Best
Julien

**Comment by lesgourg** [comment]
P.S. this means that when you want to match a cosmological model given in a cosmomc-based paper to an input file for CLASS (or for CAMB, it is actually the same thing), you cannot rely on matching the value of "theta": you must match the other parameters, plus H0...

**Comment by borisbolliet** [comment]
Hi Julien, 

Thank you very much ! 
("angular scale" not "sound speed", of course ! :-)) 

Yes, than I am pretty sure that theta_s (CLASS) is theta_star (in Planck tables). 

Good to know!
Boris

**Comment by borisbolliet** [comment]
PS: see definition of theta_star (Planck)  in line 29 of table 1 of [https://arxiv.org/pdf/1303.5076.pdf](https://arxiv.org/pdf/1303.5076.pdf) (Planck 2013 Cosmo. Param.)
