### ISSUE TITLE
Warm dark matter power spectrum at large scales

### ISSUE THREAD

**Issue by julianheeck** [lesgourg/class_public#162]
Hello,

we have been trying to run CLASS to obtain the power spectrum of one warm dark matter particle (thermal relic) of keV mass. Using the Fermi-Dirac distribution with a rescaled temperature (T_ncdm = 0.1) gives the known suppression of small scales compared to cold DM, kicking in around 0.1 Mpc for keV mass. This is all fine and matches literature benchmarks for thermal relic DM.

However, going to smaller momenta (larger scales) surprisingly also shows a deviation of the power spectrum compared to CDM, see picture below. 
![thermal_relic](https://user-images.githubusercontent.com/30832805/29072560-7376d70e-7c48-11e7-9905-ffb5493259e3.jpg)
For a thermal relic of mass 3.3 keV, this effect happened at scales below k = 10^-4 h/Mpc. We used the pk_ref.pre precision file, otherwise default parameters, and specified the WDM abundance (no cold DM), so CLASS rescales the distribution accordingly. The power spectrum is calculated directly via the C code, no wrapper.

This behaviour is quite weird; is there any approximation used in CLASS that would forbid us to go to such small momenta?

Any help is appreciated. Thanks in advance!

**Comment by miguelzuma** [comment]
It looks like you are using different gauges for each model. The
differences at very low k between synchronous and Newtonian gauge are a
well known feature, and completely artificial (see Dodelson's book)

**Comment by julianheeck** [comment]
Dear Miguel,

thanks for your quick reply. We set the gauge to Newtonian in both cases, but you are right, it very much looks like it is related to that.

**Comment by lesgourg** [comment]
Hi Julian, to add up on Miguel's reply, the matter power spectrum P(k) in the output of CLASS can in principle be given by taking the square of:

1. the total matter fluctuation in the synchronous gauge: delta_syn
2. the total matter fluctuation in the newtonian gauge: delta_new
3. a gauge-invariant definition delta_gi that is often found (e.g. books of Weinberg, Durrer...) 

For large k, they are all asymptotically equal. For small k, delta_syn=delta_gi has the behaviour of your orange curve, while delta_new has the behaviour of your blue curve.

Initially CLASS was computing P(k) from 1. when gauge=synchronous (default), and from 2. when gauge=newtonian. Then, we changed the behaviour in such way that for any chosen gauge, the output P(k) is always computed from 3, and hence always identical to the synchronous one.

The fact that by setting gauge=newtonian and using non-cold-dark-matter (ncdm) you find the blue curve is a sign that we might have an inconsistency somewhere: maybe we are doing the transformation from 2 to 1 in the general case but not when there is ncdm. We should have a look and check this!

Anyway, it seems that you expect an output behaving like the orange curve at low k. Hence, until we have time to investigate and correct this, I expect that you will get the result you want by setting gauge=synchronous always (or not setting anything since this is the default).

**Comment by julianheeck** [comment]
Hi Julien,
Thanks for the explanation. We only set the gauge to Newtonian because otherwise CLASS complained when we set the abundance of CDM to zero for the warm DM case.

**Comment by lesgourg** [comment]
Yes because the synchronous gauge is defined (as usual) as "comoving with cdm", and hence requires omega_cdm>0, but no worry: you can set the gauge to 'synchronous' and set omega_cdm=1.e-10 or 1.e-20. We do that often, it works well and it is like having no cdm at all.

**Comment by julianheeck** [comment]
Yeah, I figured it was defined in the CDM rest frame, which is no longer well defined without CDM. Thanks for the suggestion of using a tiny CDM part anyways, we might come back to this later.

I'll close this thread for now because I think the problem has been identified.

Thanks a lot for your time and help!
