### ISSUE TITLE
Do forecast with CLASS

### ISSUE THREAD

**Issue by mahtaparsa** [lesgourg/class_public#166]
Dear all, 
Is it possible to do forecast with CLASS (is there any Fisher matrix code in CLASS to do forecast?)
For example, can hi-class be helpful in this case? It seems that it is appropriate for Horndeski theory. I want to know if hi-class can do forecast for all cosmological models (every new physics). Or if, in general there is a Fisher matrix code for doing forecast in CLASS ?

**Comment by brinckmann** [comment]
Hi,
We are working on a fisher matrix approach in MontePython. It will be available soon, in the next release.
Best,
Thejs

**Comment by miguelzuma** [comment]
hi_class is a CLASS extension for modified gravity, but otherwise equivalent to CLASS. It takes a similar input and gives the same output in terms of files/observables. Whatever tool you can interface with CLASS can be used for hi_class.

To explore the parameter space of models (e.g. to compare with observations or do forecasts) you need to interface CLASS/hi_class with MontePython or some other software. For a Fisher matrix analysis you can take the Fisher derivatives directly from the code output (by computing the models with small variations and using finite differences), in case you don't want to wait for the next MontePython release. You might also want to look at https://github.com/damonge/GoFish, which is a forecast code for CLASS (I have never used it myself, though)
