### ISSUE TITLE
Comparing CAMB vs CLASS now that CAMB has a python wrapper

### ISSUE THREAD

**Issue by tmcclintock** [lesgourg/class_public#189]
CAMB now has a python wrapper with documentation(!) found [here](http://camb.readthedocs.io/en/latest/camb.html). With this I am hoping to compare the basic outputs of the two.

@lesgourg I am looking to reproduce figure 3 from your paper linked [here](https://arxiv.org/abs/1104.2934). If I run both codes out of the box on a basic LCDM I get this:

![figure_1](https://user-images.githubusercontent.com/10226392/33727121-5bba5528-db34-11e7-8107-6062d12f2a80.png)

The discrepancy grows to ~5% at low k if I try a wCDM cosmology. I'm wondering if this has to do with the accuracy settings you described in your paper. Where do I look in the docs to see how to set these in `classy`? Thank you.

**Comment by ThomasTram** [comment]
Hi Tom

The discrepancy at small k is due to two things I believe:

1)   Different definition on what to include in the matter power spectrum. CLASS uses CDM, baryon and the non-relativistic fraction of any NCDM component. In CAMB it depends on the value transfer_power_var, with the choices being: 
{2: CDM, 7: CDM+baryon+neutrino, 8: CDM+baryon, 9: CDM+baryon+neutrino+de perts}
Number 7 is closest to CLASS, but there can still be a difference for small masses and large redshifts.

2)   In CLASS, a gauge transformation is being done into a frame co-moving with the matter. This is a slightly different gauge than the synchronous gauge that CAMB uses due to the velocities of baryons and massive neutrinos relative to the CDM particles. You can disable this gauge transformation by commenting the line 
````
ppw->delta_m += 3. *ppw->pvecback[pba->index_bg_a]*ppw->pvecback[pba->index_bg_H] * ppw->theta_m/k2;
````
which is around 5226 in perturbations.c.

Cheers,
Thomas

**Comment by tmcclintock** [comment]
Thanks for your input @ThomasTram. I'll see if I can get good agreement with these changes. The main reason I bring this up is because in the LSST Core Cosmology Library we plan on allowing users to switch between the two codes. Obviously this isn't trivial if we want to understand the consequences of such a switch.

**Comment by tmcclintock** [comment]
@xzackli wow this is great! Thanks for making this. Looking at cells 2 and 19, which settings were important for getting good agreement? Did you make CLASS act like CAMB or the other way around? Last q - did any of the settings you specified noticeably affect performance?

**Comment by xzackli** [comment]
I haven't looked too hard into which parameters do what, at the moment I just need to believe that CLASS and CAMB handle high ells the same way. To do this, I used the high precision CAMB parameters in 1104.2934 and used cl_ref.pre settings for CLASS. This is not how either code behaves out of the box! 

I didn't look too hard into which parameters were important, but I imagine the big things are `k_max_tau0_over_l_max` and halofit parameters,

```  
'halofit_k_per_decade' : 3000.,
    'l_switch_limber' : 40.,
    'accurate_lensing':1,
    'num_mu_minus_lmax' : 1000.,
    'delta_l_max' : 1000.,
```
I also disabled any massive neutrinos because that's another set of precision parameters to worry about.

**Comment by xzackli** [comment]
It might be useful for the community to have some sort of agreed-upon precision parameters `lsst.pre` for P(k) and galaxy counts up to forecasted LSST accuracy. If I'm writing a paper using CLASS, I'd love to say that I ran CLASS with "typical LSST precision settings" and then cite some paper.

**Comment by tmcclintock** [comment]
You can expect that in the CCL paper that is due out in the near-ish future. I believe you can read a draft of it [here](https://github.com/LSSTDESC/CCL/tree/ccl_paper/doc/ccl_paper).

**Comment by tmcclintock** [comment]
Or at least, something along those lines :-P.

**Comment by tmcclintock** [comment]
Also I guess we can close this.
