### ISSUE TITLE
classy with pycamb defaults for neutrinos

### ISSUE THREAD

**Issue by zausl** [lesgourg/class_public#218]
Hi,
`pycamb` default settings for neutrinos are:
- `neutrino_hierarchy='degenerate'`
- `num_massive_neutrinos=1`
- `mnu=0.06`
- `nnu=3.046`

How can I put these into the classy parameter dictionary?
I tried using `N_ncdm=1` and `m_ncdm=0.06`. However, when doing so I get the error:
`Error in Class: Class did not read input parameter(s): m_ncdm`

What am I doing wrong? Do I need to specify other parameters?

Thank you very much,
Lukas

**Comment by lesgourg** [comment]
If you have passed N_ncdm=1 then there should be no problem with passing m_ncdm=0.06. Here is anyway the full set of parameters that I would recommend for matching the Planck baseline model, which is probably the same as the pycamb baseline:
N_ur = 2.0328
N_ncdm = 1
m_ncdm = 0.06
The first one says "2 ultra-relativistic neutrinos" (a bit more than 2 due to the usual corrections from high-precision neutrino decoupling studies); the second one says "one massive neutrino" (= non-cold dark matter); the 3rd one gives the mass in eV. These settings will give you the expected Neff=3.046 (summed over both massless and massive species). If you still have a problem please send you full list of input parameters for cross-check, there must be something else wrong, maybe just a typo in your parameter names.

**Comment by zausl** [comment]
Thanks for the quick answer, Julien!
I've pulled a clean version and recompiled and it indeed works.

(Previously, when I wanted to run classy with the `cl_ref.pre` parameters and otherwise default classy parameters it complained about not reading the `tol_ncdm` parameters so I changed `input.c` to force classy to read them, which backfired now upon changing `N_ncdm`...)
