### ISSUE TITLE
Units of cross-correlations

### ISSUE THREAD

**Issue by DavidFigueruelo** [lesgourg/class_public#304]
Hello everyone,

I am calculating several C_l  cross correlations and i am changing the format option of

7c) in all output files, do you want columns to be normalized and ordered with
    the default CLASS definitions or with the CAMB definitions (often idential
    to the CMBFAST one) ? Set 'format' to either 'class', 'CLASS', 'camb' or
    'CAMB' (default: 'class')

format = class or camb

While I see the difference in the value of C^TT_l  for example, I always obtain the same value for things like `T-dens[1] `  using class or camb in format. Therefore, what are the units  of `T-dens[1] ` in which it always gives the result  and is it possible to change to /mu K?

Thank you!

**Comment by ShazAlvi** [comment]
Hi. Did you find an answer to your question?

**Comment by Stefan-Heimersheim** [comment]
Hello, Julien commented a bit on the outputs [here](https://github.com/lesgourg/class_public/issues/322#issuecomment-613941965), not sure if it solves your concrete problem though.

**Comment by ShazAlvi** [comment]
Hi, Thanks for the quick comment. I did see the other thread. Accordingly, one should multiply Cl_TG with 2.7255e6 to get it in the units of micro-kelvin. So the spectrum should change when the output format is changed from CLASS to CAMB, np? But, as the OP pointed out, there is not difference. 

My particular question is related to the cosmic variance error bars for Cl_TG, calculated as:
![image](https://user-images.githubusercontent.com/63428526/89798765-e1b4fc00-db2c-11ea-83a7-fae6368cc4b0.png)
But they are coming out to be wrong so I am investigating a possible error in units in my calculation.

**Comment by Stefan-Heimersheim** [comment]
Are you using `class` from the command line or the python wrapper?

In any case, could you post the code for a simple example demonstrating the error, together with the reference you are comparing to?

Best,
Stefan

**Comment by ShazAlvi** [comment]
Here is the parameter list from CLASS ini file,

```
100*theta_s = 1.04090
T_cmb = 2.7255
omega_b = 0.02216
N_ur = 3.046
omega_cdm = 0.1197
Omega_dcdmdr = 0.0
Gamma_dcdm = 0.0
N_ncdm = 0
ncdm_psd_filenames = psd_FD_single.dat
ncdm_psd_parameters = 0.3 ,0.5, 0.05
Omega_ncdm =
T_ncdm =
ksi_ncdm =
deg_ncdm =
Quadrature strategy =
Maximum q =
Omega_k = 0.
Omega_fld = 0
Omega_scf = 0use_ppf = yes
c_gamma_over_c_fld = 0.4
w0_fld = -0.9
wa_fld = 0.
cs2_fld = 1attractor_ic_scf = yes
scf_parameters = 10.0, 0.0, 0.0, 0.0, 100.0, 0.0
scf_tuning_index = 0
Omega_idm_dr = 0.
m_idm = 1.0e11
xi_idr =
stat_f_idr = 0.875
a_idm_dr = 0.
b_idr =
nindex_idm_dr =
idr_nature =
alpha_idm_dr = 1.5
beta_idr = 1.5
YHe = BBN
recombination = RECFAST
reio_parametrization = reio_camb
tau_reio = 0.0952

reionization_exponent = 1.5
reionization_width = 0.5
helium_fullreio_redshift = 3.5
helium_fullreio_width = 0.5binned_reio_num = 3

binned_reio_z = 8,12,16
binned_reio_xe = 0.8,0.2,0.1
binned_reio_step_sharpness = 0.3

many_tanh_num = 2
many_tanh_z = 3.5,11.3
many_tanh_xe = -2,-1
many_tanh_width = 0.5

reio_inter_num = 8
reio_inter_z =   0,  3,  4,   8,   9,  10,  11, 12
reio_inter_xe = -2, -2, -1,  -1, 0.9, 0.5, 0.1,  0

annihilation = 0.

annihilation_variation = 0.
annihilation_z = 1000
annihilation_zmax = 2500
annihilation_zmin = 30
annihilation_f_halo= 20
annihilation_z_halo= 8

on the spot = yes

decay = 0.

output = tCl,pCl,dCl,mPk,mTk

extra metric transfer functions =

Nbody gauge transfer functions =

non linear = halofit

pk_eq =

feedback model =
eta_0 =
c_min =

modes = s

lensing = no

tensor method =

ic = ad

gauge = Newtonian

P_k_ini type = analytic_Pk

k_pivot = 0.05

ln10^{10}A_s = 3.0973


n_s = 0.9655

alpha_s = 0.

f_bi = 1.
n_bi = 1.5

f_cdi=1.

f_nid=1.
n_nid=2.
alpha_nid= 0.01

c_ad_bi = 0.5

c_ad_cdi = -1.

c_bi_nid = 1.

r = 1.
n_t = scc
alpha_t = scc

potential = polynomial

V_0=1.e-13
V_1=-1.e-14
V_2=7.e-14
V_3=
V_4=

H_0=1.e-13
H_1=-1.e-14
H_2=7.e-14
H_3=
H_4=

phi_end =

full_potential = polynomial


Vparam0 =
Vparam1 =
Vparam2 =
Vparam3 =
Vparam4 =

k1=0.002
k2=0.1

P_{RR}^1 = 2.3e-9
P_{RR}^2 = 2.3e-9

P_{II}^1 = 1.e-11
P_{II}^2 = 1.e-11
P_{RI}^1 = -1.e-13
|P_{RI}^2| = 1.e-13

special_iso =


custom1 = 0.05     # In the example command: k_pivot
custom2 = 2.215e-9 # In the example command: A_s
custom3 = 0.9624   # In the example command: n_s
custom4 = 2e-10    # In the example (with tensors) command: A_t
custom5 = -0.1     # In the example (with tensors) command: n_t

l_max_scalars = 2500
l_max_tensors = 2500
l_max_lss = 500

P_k_max_1/Mpc = 10

z_pk = 0.5

z_max_pk = 2.5

selection = gaussian
selection_mean = 0.490,0.901,1.329
selection_width = 0.5
selection_bias = 
selection_magnification_bias =
non_diagonal=1

dNdz_selection = 'analytic'

dNdz_evolution = 

headers = yes

format = class

write background = yes

write thermodynamics = yes

k_output_values = #0.01, 0.1, 0.0001

write primordial = no

write parameters = yeap

write warnings =

input_verbose = 1
background_verbose = 1
thermodynamics_verbose = 1
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
spectra_verbose = 1
nonlinear_verbose = 1
lensing_verbose = 1
output_verbose = 1
```
The error is calculated as per the equation, 
![image](https://user-images.githubusercontent.com/63428526/89802241-8a655a80-db31-11ea-8cae-c305891f2bff.png)
Where the Cl's for density and temperature are taken from the CLASS output file which is attached to this message. 
[CLASS_TG_LISW_Default_3Bin_0_490_0_901_1_329_SD_0_5 .txt](https://github.com/lesgourg/class_public/files/5051933/CLASS_TG_LISW_Default_3Bin_0_490_0_901_1_329_SD_0_5.txt)

I am not comparing to any reference but the error bars ($+-\sqrt{\Delta Cl_{AB}.^2}$) I am getting are far too large I think. Here is the plot of the error bars with the CLASS Cl_TG power spectrum. 

![image](https://user-images.githubusercontent.com/63428526/89803860-acf87300-db33-11ea-95aa-de74038615be.png)

**Comment by ShazAlvi** [comment]
I will add that although the graph contains two TG power spectra, as it can be seen in the legend, I am only using the CLASS power spectra for error bars.

**Comment by ShazAlvi** [comment]
One other thing: To evaluate this curve, the following parameters are used in the precision.h file, 
class_precision_parameter(perturb_sampling_stepsize,double,0.01)
class_precision_parameter(transfer_neglect_delta_k_S_t0,double,30)

**Comment by Stefan-Heimersheim** [comment]
Okay, so first let me say that I didn't work with number count before so I'm just trying to debug the CLASS outputs.
Indeed, the cross correlations `T-dens[1]` are always given in CLASS units, independent of the `format` used.

The bug(?) is in `output.c`, around line 1470 (`if (pop->output_format == camb_format)`). The CAMB format is only applied to tt, te, ee, bb, pp, tp and ep.

So if you want everything in uK, you can take Cl_TT from `camb` format or multiply the `class` ones by Tcmb_uK**2. To get Cl_TG in uK you manually need to multiply it by T_cmb_uK in any case:

    Tcmb_uK = 2.7255e6 
    ell = output_camb_format[0]
    Cl_TT =  output_class_format[1] # == output_camb_format[1]/Tcmb_uK**2
    Cl_TT_uK =  output_camb_format[1] # == output_class_format[1]*Tcmb_uK**2
    Cl_TG = output_camb_format[10] # == output_class_format[10]
    Cl_TG_uK = output_camb_format[10]*Tcmb_uK # == output_camb_format[10]*Tcmb_uK
    Cl_GG = output_camb_format[5] # == output_class_format[5]
    sigma_CV = np.sqrt(4*np.pi/(2*ell+1)*(Cl_TG**2+Cl_GG*Cl_TT))
    sigma_CV_uK = np.sqrt(4*np.pi/(2*ell+1)*(Cl_TG_uK**2+Cl_GG*Cl_TT_uK))

To the question of why the error bars are so large, it looks like Cl_GG is just much larger than TG and TT so that it dominates the error bars. Here is a plot of the products of the power spectra, TT*GG is much larger and makes the CV so large. _Note: This was without the precision settings._

    plt.plot(ell, Cl_TT*Cl_GG, label=r'$C_\ell^{TT}\cdot C_\ell^{GG}$')
    plt.loglog(ell, Cl_TG**2, label=r'$(C_\ell^{TG})^2$')
    plt.legend()
    plt.xlim(0, 500)
    plt.xlabel(r"$\ell$")
    plt.ylabel(r"$C_\ell^2$")
    plt.tight_layout()
    plt.show()

![Figure_1](https://user-images.githubusercontent.com/40799217/89871302-7ebc7700-dbb7-11ea-8568-a8f153e79f04.png)

My errorbars are a bit different but that might be related to the precision settings (?) `plt.errorbar(ell, Cl_TG, yerr=sigma_CV)`:
![screenshot_2020-08-11_09-50-17](https://user-images.githubusercontent.com/40799217/89871705-29349a00-dbb8-11ea-91fb-4b3bd39f7b3c.png)

So I would guess that TG just has large error bars due to the large value of GG compared to TG. I never saw a paper with a Cl_TG plot to compare to either.

I hope this helps,
Stefan

**Comment by ShazAlvi** [comment]
Thanks for the detailed reply. One quick question: Did you use the data file I attached for the plot or did you generate your own based on the parameters I gave? I am trying to reproduce the curve and error bars that you get.

**Comment by Stefan-Heimersheim** [comment]
Ah right, I didn't use your data file, I generated them with your params file. I attached my files:

[issue02_cl.txt](https://github.com/lesgourg/class_public/files/5056452/issue02_cl.txt)
[issue01_cl.txt](https://github.com/lesgourg/class_public/files/5056454/issue01_cl.txt)

**Comment by Stefan-Heimersheim** [comment]
Here's the script I used (renamed to txt because GitHub) and the plot of your file with it:

[plot.txt](https://github.com/lesgourg/class_public/files/5056483/plot.txt)
![Figure_1](https://user-images.githubusercontent.com/40799217/89888894-0662af80-dbd1-11ea-96ba-a5c09438ef0b.png)

**Comment by ShazAlvi** [comment]
Thanks for sharing your results and the code. I had a look at the code that you used to, I want to confirm if what I notice is a bug or I am understanding it wrong. In your code, 
```
Cl_TT =  output_camb_format[1]/Tcmb_uK**2
Cl_TT_uK =  output_camb_format[1] # == output_class_format[1]*Tcmb_uK**2
```
In the above lins, the term Tcmb_uK**2 should be multiplied with the line below. Right? Because you want to get the CLASS outoput from the file in uK**2? 
Here, TG is being treated correctly. 
```
Cl_TG = output_camb_format[10] # == output_class_format[10]
Cl_TG_uK = output_camb_format[10]*Tcmb_uK # == output_camb_format[10]*Tcmb_uK
```

Just confirming. If this is the case, then out results agree with the data that I attached in the previous post. Also, if what I point out is correct than the plot which compares the two terms in the error equation also changes according to your code. This is what I am getting, 
![image](https://user-images.githubusercontent.com/63428526/89898414-f81c8f80-dbe0-11ea-83bd-b031a6460f35.png)
Compartively, the poduct of TT and GG are larger so it still explains the size of the error bars.

**Comment by Stefan-Heimersheim** [comment]
OK, that's confusing because the `camb` format in CLASS is a bit inconsistent. I think my code was right but I'm not very confident. If I understand the format correctly, then `format = class` returns the TT power spectrum in relative units (i.e. deltaT/T) and `format = camb` in absolute units (deltaT). This makes sense with `class` TT values being around 10^{-10} while the `camb` values are around a few hundred uK. To convert you multiply deltaT/T by T, i.e. the `class` values by T_cmb = 2.725e6 squared, so that

    output_camb_format[1] == output_class_format[1]*Tcmb_uK**2

and then I get

    Cl_TT =  output_camb_format[1]/Tcmb_uK**2
    Cl_TT_uK =  output_camb_format[1]

or

    Cl_TT =  output_class_format[1]
    Cl_TT_uK = output_class_format[1]*Tcmb_uK**2

For the density cross-correlations everything seems to be in `class` format, even if you request `format = camb`.

Best,
Stefan

**Comment by ShazAlvi** [comment]
The file that I provided to you has the power spectra in CLASS units. So I think the multiplication was not required in the code. You can just use the values directly and no conversation was needed.

**Comment by Stefan-Heimersheim** [comment]
Ah my bad, I treated it as CAMB units!

**Comment by Stefan-Heimersheim** [comment]
I get exactly your plots now, treating your file (correctly) as `class` format:

![Figure_1](https://user-images.githubusercontent.com/40799217/89901927-16d15500-dbe6-11ea-8a6f-39f6ac069d7b.png)
[plot.txt](https://github.com/lesgourg/class_public/files/5057185/plot.txt)

So yeah your plots seem right, it's just that the CV error on TG seems to actually be that large (as discussed in the plots above).

**Comment by ShazAlvi** [comment]
Thank you so much for giving your time @Stefan-Heimersheim. I would like to check one more thing: Could you please provide the ini file that you used in the earlier plots?

**Comment by Stefan-Heimersheim** [comment]
Here's the file. It should be identical to the one you posted except for the `format = camb` (I did 2 runs, one for each format). I ran it with only the `spectra.c` changes from [here](https://github.com/lesgourg/class_public/issues/231#issuecomment-418629718), not any other changes.

[issue_ini.txt](https://github.com/lesgourg/class_public/files/5062145/issue_ini.txt)

**Comment by ShazAlvi** [comment]
Thanks, @Stefan-Heimersheim .
