### ISSUE TITLE
How to use Class for new dark energy equation of state A/A+(1-A)a^-3(1+@)?

### ISSUE THREAD

**Issue by azamctp** [lesgourg/class_public#31]
Hi
I want to use class for a new dark energy equation what modifications should i make to class?
I tried modifying the code by using new equation in background.c instead of w=w0+wa(1-a/ao)
The exact changes that i made are..
/** using equation of state w=A/A+(1-A)a^-3(1+@) A=w0 and @=wa**/
 if (pba->has_fld == _TRUE_) {
    pvecback[pba->index_bg_rho_fld] = pba->Omega0_fld * pow(pba->H0,2)
      *1/pow((pba->w0_fld+((1-pba->w0_fld)*(pow(a_rel,3*(1+pba->wa_fld))))),(double)(1/(1+pba->wa_fld)));
    rho_tot += pvecback[pba->index_bg_rho_fld];
   p_tot += ((pba->w0_fld)/(pba->w0_fld+(1-pba->w0_fld)*(pow(a_rel,3*(1+pba->wa_fld))))) * pvecback[pba->index_bg_rho_fld];
  }

but when i run it using lcdm.ini file i got following error msg 
Error running background_init 
=>background_init(L:593) :error in background_solve(ppr,pba);
=>background_solve(L:1499) :error in generic_integrator(background_derivs, tau_start, tau_end, pvecback_integration, &bpaw, ppr->tol_background_integration, ppr->smallest_allowed_variation, &gi);
=>generic_integrator(L:112) :error in rkqs(&x, h, eps, &hdid, &hnext, derivs, parameters_and_workspace_for_derivs, pgi);
=>rkqs(L:156) :condition (xnew == *x) is true; stepsize underflow at x=nan

 I know that i should make some modifications in perturbations.c but  i cant understand how?
Please help!

Thanks
Azam

**Comment by lesgourg** [comment]
Hi Azam,
I think that your formulas for rho_fld and p_fld are not self-consistent. Indeed, any formula that you pass there must be compatible with the equation of conservation of energy, rho' = - 3 a'/a (rho+p). If I take your expression for p as a function of rho, and plug in in this equation, I don't think that the integral gives what you wrote for rho(a). There are easy cases in which the integral can be performed analytically. For instance "p = w0 rho" gives "rho \propto a^[-3(1+w0)]". A more complicated case is the one built in the public code, where "p = [w0+wa(1-a/a0)] rho", and rho(a) obeys to a more complicated expression with an exponential. If you have a more complicated model in mind, either there is an analytic solution, and you can just modify the equations for p_fld, rho_fld; or there is not simple analytic solution and you need to integrate things numerically. In that case you should create a new species and encode its equation of conservation of energy as a new equation to be integrated by the background module. In any case, assuming that you successfully modified everything, note that the code will complain if your new species has a non-negligible density at early times: this is because the solution of differential equation is taken from initial conditions that assume radiation domination at high redshift.
