### ISSUE TITLE
Increasing sampling of mPk

### ISSUE THREAD

**Issue by arkabanerjee** [lesgourg/class_public#32]
Hi,

I would like to increase the number of values of k at which CLASS outputs mPk, dTk, and vTK. Which part do I need to modify to be able to do that?

Thanks,

Arka

**Comment by ThomasTram** [comment]
Hi Arka,

you probably do not have to modify anything except your input .ini file. The maximum k at which ```mPk,dTk,vTk``` is computed is set by ```P_k_max_h/Mpc``` *or* ```P_k_max_1/Mpc```. This is explained in ```explanatory.ini```, point 2 in the section *define format of final spectra*. The resolution of the k vector is set automatically by the code, and you probably do not need to change it. However, if you do need to change it, that can also be accomplished from the .ini file. The relevant parameters are   
```k_min_tau0 (=0.1)```
```k_max_tau0_over_l_max (=2.4)```
```k_step_sub (=0.05)```
```k_step_super (=0.002)```
```k_step_transition (=0.2)```
```k_step_super_reduction (=0.1)```
```k_per_decade_for_pk (=10.)```
```k_per_decade_for_bao (=70.)```
```k_bao_center (=3.)```
```k_bao_width (=4.)```
I have put their default values in parenthesis. Note however, that changing these values can have a dramatic impact on the performance of the code, so be careful.

Cheers,
Thomas

**Comment by lesgourg** [comment]
Hi Arka,
I thank Thomas for answering, he gave the essential elements. Maybe I can try to be more specific. There are 2 cases:

1) you are not interested in CMB, and in the 'output =....' entry of your input file, you have only quantities like 'mPk', 'dTk', 'vTk', and not 'tCl', 'pCl'...
In that case the maximum k value is set (as Thomas said) by 'P_k_max_h/Mpc' or 'P_k_max_1/Mpc', the minimum value is probably OK for you (if not, you can decrease 'k_min_tau0'), and the sampling step is controlled by just two parameters that you can decrease: 'k_per_decade_for_pk' (10 by default) is the number of k values per logarithmic k step, when you are far from the BAO region. Increase it e.g. to 40 and you'll get a high resolution power spectrum. 'k_per_decade_for_bao' (70 by default) is the same but in the BAO region: it allows to get a better resolution in the BAO region than in the smooth region. You can ignore 'k_bao_center' and 'k_bao_width', unless you want to customise what the code calls "the BAO region".

2) you are interested in CMB, and in the 'output =....' entry of your input file you have both quantities like 'mPk', 'dTk', 'vTk', and like 'tCl', 'pCl'... In that case CLASS first defines a k-sampling in the region defined by 'k_min_tau0' and 'k_max_tau0_over_l_max'. In that region, the sampling will automatically be high, because the CMB calculation requires high resolution. Above that range, the parameters described above become relevant and define the sampling until the value set by  'P_k_max_h/Mpc' or 'P_k_max_1/Mpc'. [This means that a cheap way to get a better sampling without having to play with the sampling parameters described above is just to include 'tCl' in your calculation].

Also note that when you have some doubts about the meaning of precision/sampling parameters, you can look at the file 'include/common.h' : it includes the full list of these parameters with some comments explaining their definition. When you have doubts about the default values of the same parameters, you can check them in the file 'source/input.c',
