### ISSUE TITLE
(w0, wa) in classy

### ISSUE THREAD

**Issue by gouyoub** [lesgourg/class_public#324]
Hello,

It is possible to set the values for the dark energy equation of state (w0, wa) while using the standard initialization file, with w0_fld and wa_fld. But when I try to pass these cosmological arguments with classy, it does not recognize the parameters. Is there a way to set these parameters while using classy ?

cosmo_w0 = Class()
cosmo_w0.set({'w0_fld' : -1.1, 'wa_fld' : -0.3})
cosmo_w0.compute()

Error : 
CosmoSevereError                          Traceback (most recent call last)
<ipython-input-17-6a5a9bdfaf4a> in <module>()
     63 cosmo_w0 = Class()
     64 cosmo_w0.set({'w0_fld' : -1.1, 'wa_fld' : -0.3})
---> 65 cosmo_w0.compute()

classy.pyx in classy.Class.compute()

CosmoSevereError: 

Error in Class: Class did not read input parameter(s): w0_fld, wa_fld

Thank you,
Sylvain GB.

**Comment by lesgourg** [comment]
Dear Sylvain,
The syntax for passing parameters through the input file and through classy is the exact very same one, because there is a unique parser in Class, not one for each method. All set of cosmological parameters that would work in the input file automatically work in the classy input, and vice-versa: this is just a structural fact.
In both the input file and the wrapper, w0_fld and wa_fld are read _only if you state that there is a fluid_ (which is distinct from a cosmological constant: in principle you could have a universe with only one of them, or both, or none). This means that Omega_fld must be non-zero, and either fixed to a value of your choice or adjusted by the code to match the budget equation. You can read this logic in explanatory.ini, section 8a). To ask the code to match the budget equation with Omega_fld instead of a cosmological constant, you must set Omega_Lambda=0. You have this line somewhere in your input file where you tested w0_fld and wa_fld, and you must also pass it to the classy input, because it is not the default (the default is: Omega_fld=0 and Omega_Lambda adjusted).
Sorry if this was not clear. I will add a warning in the parser that will write such a reminder when the user passes w0_fld and wa_fld while sticking to the default Omega_fld=0 value.

**Comment by gouyoub** [comment]
Great, thanks a lot for the answer.

Sylvain.
