### ISSUE TITLE
CMB lensing potential in redshift bin 

### ISSUE THREAD

**Issue by fbianchini** [lesgourg/class_public#33]
Hi everybody,

I would like to evaluate the CMB lensing potential C_l^{phiphi} sourced in a given redshift bin (z_min, z_max), and possibly its cross-correlation with some LSS tracer, say C_l^{phi g}. 
Is there a quick hack to do so?

Thanks for the help and for providing such nice code!

federico

**Comment by lesgourg** [comment]
Hi Federico,

Here are the answers to the two points in your request:

1) So you want not the full C_l^{phi phi} but the contribution of lenses in a given redshift range only. Hmmm. This is not available by default, but not very difficult to get by modifying the code. As usual, it is easier to hard-code the modification for your particular purpose, than to implement this elegantly, as a new functionality available from the input file. If the former is OK, let me suggest something. In the perturbation module, the sum of the two metric potentials [phi+psi](tau,k) is stored as a source, and used later in order to compute the cmb lensing potential. Open source/perturbations.c and search for the lines:

    /* Bardeen potential PHI_A = psi in newtonian gauge */
    if (ppt->has_source_psi == _TRUE_) {

      if (ppt->gauge == newtonian)
        _set_source_(ppt->index_tp_psi) =
          pvecmetric[ppw->index_mt_psi];

      if (ppt->gauge == synchronous)
        _set_source_(ppt->index_tp_psi) =
          a_prime_over_a * pvecmetric[ppw->index_mt_alpha] + pvecmetric[ppw->index_mt_alpha_prime];
    }

You could modify things here. You just need to multiply by zero if the redhsift is not in the required range. Fortunatley, inside this function (perturb_sources), the redhsift is known and called "z", so you can write e.g.

double tophat;
if ((z< ...) || (z>...)) tophat = 0.;
else tophat=1.;

later:
_set_source_(ppt->index_tp_psi) =
          pvecmetric[ppw->index_mt_psi]*tophat;

and later

_set_source_(ppt->index_tp_psi) =
          a_prime_over_a * pvecmetric[ppw->index_mt_alpha] + pvecmetric[ppw->index_mt_alpha_prime];

If you are expert with the code, you have another option: instead of putting the top hat function in the perturbation module, you can put it in the transfer module, precisely in the line:

 sources[index_tau-index_tau_min] =
            interpolated_sources[index_tau]
            * rescaling
            * ptr->lcmb_rescale
            * pow(ptr->k[index_md][index_q]/ptr->lcmb_pivot,ptr->lcmb_tilt);

It would have some advantages, but it's slightly more difficult. In any case, if you have problems while doing one of these modifs, let us know.

2) the calculation of the correlation [total cmb_lensing_potential] x [galaxies in given bin] is already implemented by default in the code. If in the input file, you pass at least 'lCl' and 'nCl', you will ses many columns in the output file output/..._cl.dat. Look at the header: some of them are called " ##:phi-dens[#] ". That's what you need. Look at the comments one explanatory.ini in order to customise your galaxy selection function.
Maybe your project can be done by just using these correlation. If you really need the "partial lensing potential" , then you first need to tweak the code as we said  in 1).

Good luck

Julien

**Comment by fbianchini** [comment]
Hi Julien, 

let me thank you for your prompt and thorough reply!

I managed to implement the modification to the perturbation module as you suggested, with the possibility to pass the two user-defined parameters, z_min and z_max, from the input file. 
Just a little clarification: I added the new lines in the following code block
```
/* diff of Bardeen potentials PHI_A-PHI_H = psi + phi in newtonian gauge */
    if (ppt->has_source_phi_plus_psi == _TRUE_) {
...
}
```
not in the one related to the Bardeen PHI_A potential. 
You can see the CMB convergence angular power spectra for different redshift bins in the attached plot. 
![kk_z](https://cloud.githubusercontent.com/assets/6832340/5908822/2e97c736-a5ab-11e4-8fcd-e5950b76c928.png)
Are the low-l features in the spectra due to the switch to Limber approximation and how can I have control of the multipole where to use it?

I was also able to compute the cross-correlation between the CMB lensing and LSS tracers as suggested. By the way, I take advantage of this post to warn that phi-dens correlation is not computed by the Python wrapper: maybe it was supposed to be as it is.

Thanks again for providing the requested information and for all your assistance.

Cheers,
federico

**Comment by lesgourg** [comment]
Thanks Federico. Of course you did well to write your modify int he lines for phi_plus_psi and not psi: this was a typo in my mail.
I was not aware that the phi-dens correlation is not stored by the Python wrapper, while it is actually computed by CLASS. We will have to correct this in the python wrapper.
The feature you get is clearly due to Limber. You can change the l value at which Limber is switched on by playing with the parameters (that I write here with their default values):

l_switch_limber=10
l_switch_limber_for_cl_density_over_z=30

The first is for cmb lensing and refer to a critical l value, the second is for density and refers to a critical [l/z_mean_of_the_bin] value. Usually, inaccuracies come mainly from the latter, not the former. Ideally you would like to increase the second switch from 30 to a very large number, to tell the code never to use Limber for density. But then, the code becomes much slower. In the mid-term, we have in mind a modification of CLASS that would allow to discard the Limber approximation for density, while at the same time keeping the code fast. We know that it is doable, but it will take some time before we can do it and release it.
