### ISSUE TITLE
get_primordial() fails with python3

### ISSUE THREAD

**Issue by janinarenk** [lesgourg/class_public#354]
Hi, 

I've tried retrieving the primordial power spectrum through the python wrapper but it fails with python3 (python2 works fine). The problematic line is 

`if primordial_output_titles(&self.pt, &self.pm, titles)==_FAILURE_:
            raise CosmoSevereError(self.pm.error_message)`

in `python/classy.pyx` in the definition of `get_primordial()` around line 1460.

The error is 
```
classy.pyx in classy.Class.get_primordial()
TypeError: a bytes-like object is required, not 'str'
```

You can reproduce this by running 
```from classy import Class; c = Class(); c.set_default(); c.compute(); c.get_primordial()```
in python3.

Any ideas for a fix would be much appreciated :) Thanks for your help! 

Cheers,
Janina

**Comment by pstoecker** [comment]
Hi Janina,

the line that you are pointing out is actually not the culprit.

it seems that the error is just due to two lines which are swapped in their order compared to similar implementations for example in `get_thermodynamics()`. 

The lines are
```
if primordial_output_titles(&self.pt, &self.pm, titles)==_FAILURE_:
  raise CosmoSevereError(self.pm.error_message)

tmp = <bytes> titles
names = tmp.split("\t")[:-1]             # <--- need to swap
tmp = str(tmp.decode())                  # <--- need to swap
number_of_titles = len(names)
timesteps = self.pm.lnk_size
```
but should actually read
```
if primordial_output_titles(&self.pt, &self.pm, titles)==_FAILURE_:
  raise CosmoSevereError(self.pm.error_message)

tmp = <bytes> titles
tmp = str(tmp.decode())
names = tmp.split("\t")[:-1] 
number_of_titles = len(names)
timesteps = self.pm.lnk_size
```
such that thje error is just due to the fact that `"\t"` is a `str` but tmp is still a `bytes` object as it was not yet casted into a `str` such that `names = tmp.split("\t")[:-1]` fails due to a type mismatch.

Best, Patrick

**Comment by pstoecker** [comment]
I just realised that this issue was already raised in the past as #325. 

It seems that by fixing the issue the lines got swapped such that the fix needs fixing.

**Comment by janinarenk** [comment]
Ah, sorry I missed this, thanks a lot Patrick!
