### ISSUE TITLE
Missing cross-correlations with non_diagonal=Nbins-1

### ISSUE THREAD

**Issue by hsxavier** [lesgourg/class_public#37]
I want to generate nCl and sCl in several redshift bins and all their cross-correlations, but CLASS does not output dens[i]-lens[j] cross-correlations for i>j. I tried this by setting selection_mean=x,y,z... and non_diagonal=Nbins-1.

E.g: For nCl, sCl and two redshift bins I should get 10 Cls but CLASS only generates 9 -- it does not generate the dens[2]-lens[1]. 

From the output layout I would guess the dens[i]-lens[j] follows the same output scheme as the dens[i]-dens[j] and lens[i]-lens[j]. For these last two it makes sense avoid i>j (because dens[i]-dens[j] = dens[j]-dens[i]), but this is not the case for dens[i]-lens[j].

**Comment by lesgourg** [comment]
Thanks for noticing! Indeed dens[i]-lens[j] was treated as a symmetric matrix while it is obviously not! Fortunately this could be solved by changing just 4 lines in the code. I implemented the fix in the branch 2.4 on github. The fix will be propagated to the master branch very soon, but not immediately. However you could immediately try the new version of the branch 2.4 - I guess that you know how to do that, but let me recall it just in case:

If you are working with the master branch (or your own customised branch), you need to commit all your changes in order to be allowed to leave that branch. Then you can type:

git checkout 2.4

In principle git should tell you that it will now track the existing branch 'origin/2.4'
Then you can type

git pull origin 2.4

You now have the latest 2.4 branch (last change this afternoon). After a 'make clean', 'make -j', you have the new code ready. You should see all dens[i]-lens[j] columns now. Let me know if something goes wrong. Best, - Julien

**Comment by hsxavier** [comment]
Thanks for the fast correction! All Cls are in the output now. If I find anything weird with the extra Cls I will let you know.
Cheers!
