### ISSUE TITLE
Apple M1 Chip

### ISSUE THREAD

**Issue by komatsu5147** [lesgourg/class_public#384]
Not sure if this is the right place to report this, but I managed to get the Python wrapper working on the new Apple M1 machine (macbook).

First of all, the main class code compiles and runs just fine without any tweaks, as long as you turn off `OMPFLAG` in `Makefile`. If you do not need the Python wrapper, you have nothing to worry about.

The issue arises when using the Python wrapper. The reason is that the class code will be compiled by `clang` with the ARM architecture, whereas Python 3.8.5 is still using the x86 architecture. Thus, the library (libclass.a) would not be compatible with Python. Namely:

```
➜  class git:(master) ✗ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: arm64-apple-darwin20.2.0
```

```
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'x86_64'
```

To fix this, you can compile the class code with the x86 architecture. The simplest is to make this modification in Makefile:

`OPTFLAG = -O4 -ffast-math #-march=native`
=>
`OPTFLAG = -O4 -ffast-math -arch x86_64 #-march=native`

This is of course not the best thing to do because class compiled on ARM64 is faster. (If you do not need Python wrapper, don't do this!)  Now, there is new Python 3.9 which supports ARM64, but it does not support `numpy` yet. When `numpy` is supported by Python 3.9, maybe we can do all of the work on ARM64. Till then, you can use this hack to make the Python wrapper run on Apple M1 chip.

Hope this is useful.

**Comment by ThomasTram** [comment]
Hi Eiichiro

Thanks a lot for this! I have been thinking about CLASS on M1 since it was introduced - how much is the performance penalty of "Rosetta 2" for CLASS?

Cheers,
Thomas

**Comment by komatsu5147** [comment]
M1 native: 
```
➜  class git:(master) ✗ time ./class explanatory.ini
./class explanatory.ini  2.11s user 0.03s system 89% cpu 2.394 total
```

I tried this three times, and they all gave 2.11s.

Rosetta 2
```
➜  class git:(master) ✗ time ./class explanatory.ini
./class explanatory.ini  2.65s user 0.06s system 99% cpu 2.718 total
```

Three trials gave 2.65, 2.62, and 2.66s. 

Conclusion: Rosetta 2 is slower by 25%.

**Comment by lesgourg** [comment]
This is all incredibly useful, thank you!

**Comment by komatsu5147** [comment]
My pleasure - will close this.

**Comment by tsmith2** [comment]
I am running into an issue getting the classy wrapper to work on my M1 laptop (running MacOS Monterey). I think that Eiichiro's original post no longer applies since:

`Python 3.9.13 (main, Aug 25 2022, 18:24:45) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'arm64'`

and numpy is now supported in Python 3.9. I am compiling with the latest clang:

`Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

Everything runs fine on the command line, but I am getting the following error when I try to import classy:

`ImportError: dlopen(/Users/tsmith2/.local/lib/python3.9/site-packages/classy-3.2.0-py3.9-macosx-11.1-arm64.egg/classy.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (_background_at_tau)`

**Comment by komatsu5147** [comment]
Interesting. I am also using python with arm64 support:
```python
➜  class git:(master) ✗ python
Python 3.8.13 (default, Mar 28 2022, 06:13:39) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'arm64'
```
I am not using Python 3.9 yet but 3.8.13 also supports `arm64`. I've cleaned up and recompiled `class` just now, and it compiles fine without errors. 

I assume that you've also done this step after compiling `class` and before importing `classy`?
```python
➜  class git:(master) ✗ cd python 
➜  python git:(master) ✗ python setup.py install --user
```
