### ISSUE TITLE
Error while using python wrapper

### ISSUE THREAD

**Issue by ravi398** [lesgourg/class_public#387]
Dear Sir
I have compiled class with using icc 19 and python 3.6.3 . it does not return any error while i complile. But when i use python wrapper as
(base) [ravi@nova python]$ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> import scipy.special as sp
>>> from classy import Class
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/ravi/.local/lib/python3.6/site-packages/classy.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strlen
>>> exit()

it reurns error.

please help me .. what could be error.

python wrapper works fine while using gcc.

thanking you 

regards 
Ravi kumar sharma

**Comment by ThomasTram** [comment]
Hi Ravi

*The easiest solution is to just compile CLASS using gcc.*
And the next easiest solution is to use a version of Python compiled using icc if it is available. (Note that you have `[GCC 7.2.0] on linux` when you open Python).

However, you can probably get icc to work as well, but you need to modify python/setup.py. Your problem is that certain functions from Intels C library is being used, but these symbols are not found when called from gcc-compiled Python. 

If you look at the GCCPATH variable inside python/setup.py, you see that it recovers the full path of gcc's C library using the call `gcc -print-libgcc-file-name`. If icc has a similar method, you could just use that instead. Otherwise you need to manually set GCCPATH to the proper value. There may also be further issues after that one.

Cheers,
Thomas

**Comment by ravi398** [comment]
Thank you sir for your response.
