### ISSUE TITLE
Class manual website not working

### ISSUE THREAD

**Issue by astrogirl1** [lesgourg/class_public#406]
Hi, 

I am trying to get the website that contained the information on the different variables used in CLASS and also data structures. It worked for me a few days ago but I seem to get this 404 error when I try using the same site. Has there been a change, and if so where can I find all the information?

This is the link I used : https://lesgourg.github.io/class_public/class_public-2.9.0/doc/manual/html/background_8h.html#structbackground

Thank you , 
Meera

**Comment by lesgourg** [comment]
Dear Meera,
The documentation itself is updated at each new major release of CLASS. As you can see yourself, the link that you have been using is pointing at one specific function inside the specific doc of v2.9.0. This link is indeed not working since the time of the release of v3.0.0. If you always click on the link called 'online html documentation' either in https://github.com/lesgourg/class_public/wiki or in http://class-code.net, you will always reach the newest doc, since we update these links at each new release.

**Comment by astrogirl1** [comment]
AH thank you! :)
