### ISSUE TITLE
non-limber CMB lensing

### ISSUE THREAD

**Issue by damonge** [lesgourg/class_public#61]
Hi,

the CMB lensing power spectrum in the Limber and non-Limber approximation are very different from each other. Too different! (see attached). I have verified that the prediction in the Limber approximation is correct by comparing with my own code, and that the non-Limber prediction should be almost equivalent to the Limber case. I've tried to track down the bug in the code that could be causing this with no luck, but maybe there's something I'm not understanding.
![cl_limber](https://cloud.githubusercontent.com/assets/8809493/10376833/f54f235a-6df7-11e5-9ad0-7f838d318e17.png)

Regards,

David Alonso

**Comment by ThomasTram** [comment]
Hi David,

the Limber approximation is implemented for a reason, so if you turn it off you can not expect everything else to stay the same. That goes for any precision parameter in the code. The Limber approximation is used in order to reduce the number of points needed in the line-of-sight integration, and if we turn it off we get the wrong result. However, if we really want to, we can recover the correct result by tuning precision parameters. In this case it turns out that the relevant precision parameter is
````
perturb_sampling_stepsize=0.01
````
Here is plot along with an IPython Notebook to reproduce it:



![limber](https://cloud.githubusercontent.com/assets/5593952/10486962/8d01534a-7289-11e5-94b8-9a4d2e87fff6.png)

````
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
from classy import Class
import numpy as np

cosmo = []
names = ['No Limber','Limber','ImprovedNoLimber']
for name in names:
    cosmo.append(Class())
    cosmo[-1].set({'output':'lCl'})
    if name=='No Limber':
        cosmo[-1].set({'l_switch_limber':3000.})
    elif name=='ImprovedNoLimber':
        cosmo[-1].set({'l_switch_limber':3000.,
                      'perturb_sampling_stepsize':0.01})
    cosmo[-1].compute()
    
for n in range(len(names)):
    Cl = cosmo[n].raw_cl()
    Cl.viewkeys()
    l = Cl['ell']
    plt.loglog(l,l**4*Cl['pp'],lw=1)
plt.xlabel(r'$\ell$',fontsize=26)
plt.ylabel(r'$\ell^4 C_\ell^{\phi\phi}$',fontsize=26)
plt.legend(names,loc='lower left',fontsize=16)
plt.savefig('Limber.pdf')
````

**Comment by damonge** [comment]
Hi Thomas,

thanks a lot. It might be a good idea to note this clearly in the documentation (I don't think this is obvious a priori, but I may have missed it).

Cheers,

David
