### ISSUE TITLE
Scale-dependent growth factor?

### ISSUE THREAD

**Issue by aoifeboyle** [lesgourg/class_public#95]
Hello. This is more of a query than an issue. I was under the impression that in the absence of massive neutrinos, the linear growth factor (D) should be scale-independent. However, when I examine this with CLASS it seems that the growth factor output in the background file applies at low k but not at higher k values. I ran CLASS with the same parameters at z=2 and z=1. I then evolved the z=2 power spectrum to z=1 by multiplying by (D(z=1)/D(z=2))^2 (obtained from the background file). This plot shows the ratio of these two power spectra (the one directly output at z=1 by CLASS and the one evolved from z=2 manually using the D values). For the CLASS runs I just let the code use the default values for everything and only varied z_pk.

![scale_dependent_growth_factor](https://cloud.githubusercontent.com/assets/5586399/14764324/341b955c-09b4-11e6-9fab-3dd8db862a79.png)

What is the origin of this apparent scale-dependence in the growth factor? I did find a paper that gave a derivation for a scale-dependent growth factor evolution function f, and I used this to solve a differential equation to obtain a scale-dependent D value, but I was not able to reproduce the above effect using this. 

Thanks for your help!

Aoife

**Comment by aoifeboyle** [comment]
@ThomasTram Do you know anything about this? You were very helpful to me last time.

**Comment by ThomasTram** [comment]
Hi Aoife,

as you can see on the plot you are looking at a per mille effect on the matter power spectrum, so this is a really tiny effect. It is due to radiation as you can verify by changing the amount of matter to radiation (for instance by fixing the helium fraction YHe=0.25 and then vary N_ur). My guess on the physical mechanism is this: at k>k_eq the radiation transfer functions are suppressed so the gravitational potential  is slightly smaller than assumed when computing D. At large scales the perturbations are all related to each other, so it is probably equivalent to have all the energy density perturbation in matter or a part of it in matter and a part of it in radiation. I do not know if someone investigated this effect in detail, but perhaps not. You can be the first one then!

Cheers,
Thomas

**Comment by aoifeboyle** [comment]
@ThomasTram Thank you for your reply. Sorry for the delay in responding - I was on vacation. But that makes sense. Glad to have this clarified! You can close the issue now if you would like.
