### ISSUE TITLE
Wrong sign in the gauge transformation rule for  delta_fld in perturbation.c?

### ISSUE THREAD

**Issue by borisbolliet** [lesgourg/class_public#98]
Hello,

There might be a typo at line 4411 in perturbation.c (master branch):
` ppw->pv->y[ppw->pv->index_pt_delta_fld] += 3*(1.+pba->w0_fld+pba->wa_fld)*a_prime_over_a*alpha;`

which I think should be replaced by 
` ppw->pv->y[ppw->pv->index_pt_delta_fld]` -= `3*(1.+pba->w0_fld+pba->wa_fld)*a_prime_over_a*alpha;`

to be consistent with formula (3.14) of Ballesteros & @lesgourg 2010, as well as the other transformations, e.g. line 4400 for CDM:
` ppw->pv->y[ppw->pv->index_pt_delta_cdm] -= 3.*a_prime_over_a*alpha; `

Kind Regards,

Boris

**Comment by ThomasTram** [comment]
Hi,

I find that 
![image](https://cloud.githubusercontent.com/assets/5593952/15106820/b63f9b9e-15c3-11e6-851c-90bf7da1ad3d.png)
so from e.g. equation 27a of Ma&Bertschinger we should actually have
````
ppw->pv->y[ppw->pv->index_pt_delta_fld] -= 3*(1.+pba->w0_fld+pba->wa_fld-a_rel*pba->wa_fld)*a_prime_over_a*alpha;
````
However, ````a_rel```` is of probably negligible at early time. But I agree that the sign seems wrong. I just checked the effect on the Cls of switching the sign, and it had no effect at all. In fact, I had to substitute the equation with
````
ppw->pv->y[ppw->pv->index_pt_delta_fld] *= 1e10; //!!!
````
in order to produce a 10^-3 discrepancy in the Cls between Newtonian and synchronous gauge at large scales! But the formula should be corrected nevertheless. I have attached my IPython Notebook here for my own reference:
````
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from classy import Class

cosmo = {}
models = ['synchronous','newtonian']
for model in models:
    cosmo[model] = Class()
    cosmo[model].set({'output':'tCl','Omega_Lambda':0.0,'w0_fld':-0.9,'wa_fld':0.1,'gauge':model})
    cosmo[model].compute()
    
cls = cosmo['synchronous'].raw_cl()
cln = cosmo['newtonian'].raw_cl()
plt.semilogy(cls['ell'],np.abs(1.-cls['tt']/cln['tt']))
````

Cheers,
Thomas

**Comment by borisbolliet** [comment]
Thank you for this clarification,

Let's close this issue then, and maybe keep it in mind for the next public version. 

Kind regards,

Boris
